language: python
python:
  - 3.2
  - 3.3
install:
  - pip install err==2.0.0rc2 --use-mirrors
  - pip install coverage --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=dnsnative.py test_dnsnative.py
after_success:
  - coveralls
