language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -q err --use-wheel
  - pip install -q pep8 coverage coveralls pytest --use-wheel
script:
  - coverage run --source=dnsnative.py test_dnsnative.py
after_success:
  - coveralls
notifications:
  email: false
