language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -q -r requirements-test.txt --use-wheel
  - pip install -q coveralls --use-wheel
script:
  - coverage run --source dnsnative -m py.test --pep8
after_success:
  - coveralls
notifications:
  email: false
